name: update_page
on: [workflow_dispatch]

jobs: 
  update-page:
    name: copy built
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout"
      uses: actions/checkout@v3.0.2    
    - name: "Upload to GitHub pages" 
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages
        folder: export/web
        
